// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFkOUtZ-VovG64maXmapA0Ge-7noN0fgc',
    appId: '1:1046121563528:web:7fca522bfc3f70f962663d',
    messagingSenderId: '1046121563528',
    projectId: 'police-akka',
    authDomain: 'police-akka.firebaseapp.com',
    storageBucket: 'police-akka.firebasestorage.app',
    measurementId: 'G-ZZ0H8084E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1GUMvT3hfsbWMLPA30JCmm-UwwFX0I3M',
    appId: '1:1046121563528:android:c9a95aa01b0fc93462663d',
    messagingSenderId: '1046121563528',
    projectId: 'police-akka',
    storageBucket: 'police-akka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAySkWGLA0CQUkeeNvr5q59l0o-06joXlE',
    appId: '1:1046121563528:ios:3b5030766962fcd462663d',
    messagingSenderId: '1046121563528',
    projectId: 'police-akka',
    storageBucket: 'police-akka.firebasestorage.app',
    iosBundleId: 'com.example.policeAkka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAySkWGLA0CQUkeeNvr5q59l0o-06joXlE',
    appId: '1:1046121563528:ios:3b5030766962fcd462663d',
    messagingSenderId: '1046121563528',
    projectId: 'police-akka',
    storageBucket: 'police-akka.firebasestorage.app',
    iosBundleId: 'com.example.policeAkka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFkOUtZ-VovG64maXmapA0Ge-7noN0fgc',
    appId: '1:1046121563528:web:da19c610c7b67aed62663d',
    messagingSenderId: '1046121563528',
    projectId: 'police-akka',
    authDomain: 'police-akka.firebaseapp.com',
    storageBucket: 'police-akka.firebasestorage.app',
    measurementId: 'G-GEEZZTY3FS',
  );
}
