import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';

// 🔥 Firebase options generated by flutterfire configure
import 'firebase_options.dart';

// 🔐 OTP Login Screen
import 'screens/auth/phone_login_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ Initialize Firebase correctly
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const PoliceAkkaApp());
}

class PoliceAkkaApp extends StatelessWidget {
  const PoliceAkkaApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Police Akka',
      theme: ThemeData(
        primarySwatch: Colors.indigo,
        scaffoldBackgroundColor: Colors.white,
      ),

      // 🚀 APP STARTS HERE
      home: const PhoneLoginScreen(),
    );
  }
}
